-- Seed de catálogos del módulo de pacientes.
-- Idempotente: todos los INSERT usan ON CONFLICT DO NOTHING.
-- Generado por scripts/generate_patient_catalogs_seed.py; no editar a mano.

-- Grupos sanguíneos (código canónico).
INSERT INTO app.blood_types (code, name, sort_order) VALUES
    ('A+', 'A+', 1),
    ('A-', 'A-', 2),
    ('B+', 'B+', 3),
    ('B-', 'B-', 4),
    ('AB+', 'AB+', 5),
    ('AB-', 'AB-', 6),
    ('O+', 'O+', 7),
    ('O-', 'O-', 8)
ON CONFLICT (code) DO NOTHING;

-- Tipos de documento (contexto USA, USCIS I-9).
INSERT INTO app.document_types (code, name, sort_order) VALUES
    ('SSN', 'Social Security Number (SSN)', 1),
    ('DRIVERS_LICENSE', 'Driver''s License', 2),
    ('STATE_ID', 'State ID Card', 3),
    ('US_PASSPORT', 'U.S. Passport', 4),
    ('FOREIGN_PASSPORT', 'Foreign Passport', 5),
    ('GREEN_CARD', 'Permanent Resident Card (Green Card)', 6),
    ('MILITARY_ID', 'U.S. Military ID', 7),
    ('TRIBAL_ID', 'Tribal Identification Card', 8),
    ('BIRTH_CERTIFICATE', 'Birth Certificate', 9),
    ('OTHER', 'Other', 10)
ON CONFLICT (code) DO NOTHING;

-- Etnias (categorías OMB 2024).
INSERT INTO app.ethnicities (code, name, sort_order) VALUES
    ('HISPANIC_OR_LATINO', 'Hispanic or Latino', 1),
    ('WHITE', 'White', 2),
    ('BLACK_OR_AFRICAN_AMERICAN', 'Black or African American', 3),
    ('ASIAN', 'Asian', 4),
    ('AMERICAN_INDIAN_OR_ALASKA_NATIVE', 'American Indian or Alaska Native', 5),
    ('NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER', 'Native Hawaiian or Pacific Islander', 6),
    ('MIDDLE_EASTERN_OR_NORTH_AFRICAN', 'Middle Eastern or North African', 7),
    ('MULTIRACIAL', 'Multiracial', 8),
    ('OTHER', 'Other', 9)
ON CONFLICT (code) DO NOTHING;

-- Países (ISO 3166-1 alpha-2 + prefijo E.164).
INSERT INTO app.countries (code, name, phone_code, is_active, sort_order) VALUES
    ('US', 'United States', '1', true, 1),
    ('CA', 'Canada', '1', true, 2),
    ('MX', 'Mexico', '52', true, 3),
    ('AL', 'Albania', '355', true, 4),
    ('AR', 'Argentina', '54', true, 5),
    ('AU', 'Australia', '61', true, 6),
    ('AT', 'Austria', '43', true, 7),
    ('BS', 'Bahamas', '1', true, 8),
    ('BD', 'Bangladesh', '880', true, 9),
    ('BE', 'Belgium', '32', true, 10),
    ('BZ', 'Belize', '501', true, 11),
    ('BO', 'Bolivia', '591', true, 12),
    ('BR', 'Brazil', '55', true, 13),
    ('BG', 'Bulgaria', '359', true, 14),
    ('CM', 'Cameroon', '237', true, 15),
    ('CL', 'Chile', '56', true, 16),
    ('CN', 'China', '86', true, 17),
    ('CO', 'Colombia', '57', true, 18),
    ('CR', 'Costa Rica', '506', true, 19),
    ('HR', 'Croatia', '385', true, 20),
    ('CU', 'Cuba', '53', true, 21),
    ('CZ', 'Czech Republic', '420', true, 22),
    ('DK', 'Denmark', '45', true, 23),
    ('DO', 'Dominican Republic', '1', true, 24),
    ('EC', 'Ecuador', '593', true, 25),
    ('EG', 'Egypt', '20', true, 26),
    ('SV', 'El Salvador', '503', true, 27),
    ('ET', 'Ethiopia', '251', true, 28),
    ('FI', 'Finland', '358', true, 29),
    ('FR', 'France', '33', true, 30),
    ('DE', 'Germany', '49', true, 31),
    ('GH', 'Ghana', '233', true, 32),
    ('GR', 'Greece', '30', true, 33),
    ('GT', 'Guatemala', '502', true, 34),
    ('GY', 'Guyana', '592', true, 35),
    ('HN', 'Honduras', '504', true, 36),
    ('HU', 'Hungary', '36', true, 37),
    ('IN', 'India', '91', true, 38),
    ('ID', 'Indonesia', '62', true, 39),
    ('IE', 'Ireland', '353', true, 40),
    ('IL', 'Israel', '972', true, 41),
    ('IT', 'Italy', '39', true, 42),
    ('JM', 'Jamaica', '1', true, 43),
    ('JP', 'Japan', '81', true, 44),
    ('KE', 'Kenya', '254', true, 45),
    ('KW', 'Kuwait', '965', true, 46),
    ('MY', 'Malaysia', '60', true, 47),
    ('MA', 'Morocco', '212', true, 48),
    ('NZ', 'New Zealand', '64', true, 49),
    ('NI', 'Nicaragua', '505', true, 50),
    ('NG', 'Nigeria', '234', true, 51),
    ('NO', 'Norway', '47', true, 52),
    ('PA', 'Panama', '507', true, 53),
    ('PY', 'Paraguay', '595', true, 54),
    ('PE', 'Peru', '51', true, 55),
    ('PH', 'Philippines', '63', true, 56),
    ('PL', 'Poland', '48', true, 57),
    ('PT', 'Portugal', '351', true, 58),
    ('PR', 'Puerto Rico', '1', true, 59),
    ('QA', 'Qatar', '974', true, 60),
    ('RO', 'Romania', '40', true, 61),
    ('RU', 'Russia', '7', true, 62),
    ('SA', 'Saudi Arabia', '966', true, 63),
    ('SN', 'Senegal', '221', true, 64),
    ('RS', 'Serbia', '381', true, 65),
    ('SG', 'Singapore', '65', true, 66),
    ('SK', 'Slovakia', '421', true, 67),
    ('ZA', 'South Africa', '27', true, 68),
    ('KR', 'South Korea', '82', true, 69),
    ('ES', 'Spain', '34', true, 70),
    ('LK', 'Sri Lanka', '94', true, 71),
    ('SR', 'Suriname', '597', true, 72),
    ('SE', 'Sweden', '46', true, 73),
    ('CH', 'Switzerland', '41', true, 74),
    ('TW', 'Taiwan', '886', true, 75),
    ('TZ', 'Tanzania', '255', true, 76),
    ('TH', 'Thailand', '66', true, 77),
    ('TT', 'Trinidad and Tobago', '1', true, 78),
    ('TN', 'Tunisia', '216', true, 79),
    ('TR', 'Turkey', '90', true, 80),
    ('UA', 'Ukraine', '380', true, 81),
    ('AE', 'United Arab Emirates', '971', true, 82),
    ('GB', 'United Kingdom', '44', true, 83),
    ('UY', 'Uruguay', '598', true, 84),
    ('VE', 'Venezuela', '58', true, 85),
    ('VN', 'Vietnam', '84', true, 86)
ON CONFLICT (code) DO NOTHING;

-- Estados y territorios de EE. UU.
INSERT INTO app.states (id, country_id, code, name)
SELECT gen_random_uuid(), c.id, s.code, s.name
FROM (VALUES
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
    ('DC', 'District of Columbia'),
    ('PR', 'Puerto Rico'),
    ('VI', 'U.S. Virgin Islands'),
    ('GU', 'Guam'),
    ('AS', 'American Samoa'),
    ('MP', 'Northern Mariana Islands')
) AS s(code, name)
JOIN app.countries c ON c.code = 'US'
ON CONFLICT (country_id, code) DO NOTHING;

-- Ciudades: 5 genéricas por estado (presentes en el dato legacy) + reales con ZIP.
INSERT INTO app.cities (id, state_id, name)
SELECT gen_random_uuid(), st.id, c.name
FROM (VALUES
    ('AL', 'Fairview'),
    ('AL', 'Georgetown'),
    ('AL', 'Madison'),
    ('AL', 'Riverside'),
    ('AL', 'Springfield'),
    ('AK', 'Fairview'),
    ('AK', 'Georgetown'),
    ('AK', 'Madison'),
    ('AK', 'Riverside'),
    ('AK', 'Springfield'),
    ('AZ', 'Fairview'),
    ('AZ', 'Georgetown'),
    ('AZ', 'Madison'),
    ('AZ', 'Riverside'),
    ('AZ', 'Springfield'),
    ('AR', 'Fairview'),
    ('AR', 'Georgetown'),
    ('AR', 'Madison'),
    ('AR', 'Riverside'),
    ('AR', 'Springfield'),
    ('CA', 'Fairview'),
    ('CA', 'Georgetown'),
    ('CA', 'Madison'),
    ('CA', 'Riverside'),
    ('CA', 'Springfield'),
    ('CA', 'Los Angeles'),
    ('CA', 'San Francisco'),
    ('CA', 'Sacramento'),
    ('CA', 'Fresno'),
    ('CA', 'San Diego'),
    ('CO', 'Fairview'),
    ('CO', 'Georgetown'),
    ('CO', 'Madison'),
    ('CO', 'Riverside'),
    ('CO', 'Springfield'),
    ('CT', 'Fairview'),
    ('CT', 'Georgetown'),
    ('CT', 'Madison'),
    ('CT', 'Riverside'),
    ('CT', 'Springfield'),
    ('DE', 'Fairview'),
    ('DE', 'Georgetown'),
    ('DE', 'Madison'),
    ('DE', 'Riverside'),
    ('DE', 'Springfield'),
    ('FL', 'Fairview'),
    ('FL', 'Georgetown'),
    ('FL', 'Madison'),
    ('FL', 'Riverside'),
    ('FL', 'Springfield'),
    ('FL', 'Fort Lauderdale'),
    ('FL', 'Tampa'),
    ('FL', 'Miami'),
    ('FL', 'Orlando'),
    ('FL', 'Jacksonville'),
    ('GA', 'Fairview'),
    ('GA', 'Georgetown'),
    ('GA', 'Madison'),
    ('GA', 'Riverside'),
    ('GA', 'Springfield'),
    ('HI', 'Fairview'),
    ('HI', 'Georgetown'),
    ('HI', 'Madison'),
    ('HI', 'Riverside'),
    ('HI', 'Springfield'),
    ('ID', 'Fairview'),
    ('ID', 'Georgetown'),
    ('ID', 'Madison'),
    ('ID', 'Riverside'),
    ('ID', 'Springfield'),
    ('IL', 'Fairview'),
    ('IL', 'Georgetown'),
    ('IL', 'Madison'),
    ('IL', 'Riverside'),
    ('IL', 'Springfield'),
    ('IL', 'Chicago'),
    ('IL', 'Joliet'),
    ('IL', 'Rockford'),
    ('IL', 'Aurora'),
    ('IL', 'Naperville'),
    ('IN', 'Fairview'),
    ('IN', 'Georgetown'),
    ('IN', 'Madison'),
    ('IN', 'Riverside'),
    ('IN', 'Springfield'),
    ('IA', 'Fairview'),
    ('IA', 'Georgetown'),
    ('IA', 'Madison'),
    ('IA', 'Riverside'),
    ('IA', 'Springfield'),
    ('KS', 'Fairview'),
    ('KS', 'Georgetown'),
    ('KS', 'Madison'),
    ('KS', 'Riverside'),
    ('KS', 'Springfield'),
    ('KY', 'Fairview'),
    ('KY', 'Georgetown'),
    ('KY', 'Madison'),
    ('KY', 'Riverside'),
    ('KY', 'Springfield'),
    ('LA', 'Fairview'),
    ('LA', 'Georgetown'),
    ('LA', 'Madison'),
    ('LA', 'Riverside'),
    ('LA', 'Springfield'),
    ('ME', 'Fairview'),
    ('ME', 'Georgetown'),
    ('ME', 'Madison'),
    ('ME', 'Riverside'),
    ('ME', 'Springfield'),
    ('MD', 'Fairview'),
    ('MD', 'Georgetown'),
    ('MD', 'Madison'),
    ('MD', 'Riverside'),
    ('MD', 'Springfield'),
    ('MA', 'Fairview'),
    ('MA', 'Georgetown'),
    ('MA', 'Madison'),
    ('MA', 'Riverside'),
    ('MA', 'Springfield'),
    ('MI', 'Fairview'),
    ('MI', 'Georgetown'),
    ('MI', 'Madison'),
    ('MI', 'Riverside'),
    ('MI', 'Springfield'),
    ('MN', 'Fairview'),
    ('MN', 'Georgetown'),
    ('MN', 'Madison'),
    ('MN', 'Riverside'),
    ('MN', 'Springfield'),
    ('MS', 'Fairview'),
    ('MS', 'Georgetown'),
    ('MS', 'Madison'),
    ('MS', 'Riverside'),
    ('MS', 'Springfield'),
    ('MO', 'Fairview'),
    ('MO', 'Georgetown'),
    ('MO', 'Madison'),
    ('MO', 'Riverside'),
    ('MO', 'Springfield'),
    ('MT', 'Fairview'),
    ('MT', 'Georgetown'),
    ('MT', 'Madison'),
    ('MT', 'Riverside'),
    ('MT', 'Springfield'),
    ('NE', 'Fairview'),
    ('NE', 'Georgetown'),
    ('NE', 'Madison'),
    ('NE', 'Riverside'),
    ('NE', 'Springfield'),
    ('NV', 'Fairview'),
    ('NV', 'Georgetown'),
    ('NV', 'Madison'),
    ('NV', 'Riverside'),
    ('NV', 'Springfield'),
    ('NH', 'Fairview'),
    ('NH', 'Georgetown'),
    ('NH', 'Madison'),
    ('NH', 'Riverside'),
    ('NH', 'Springfield'),
    ('NJ', 'Fairview'),
    ('NJ', 'Georgetown'),
    ('NJ', 'Madison'),
    ('NJ', 'Riverside'),
    ('NJ', 'Springfield'),
    ('NM', 'Fairview'),
    ('NM', 'Georgetown'),
    ('NM', 'Madison'),
    ('NM', 'Riverside'),
    ('NM', 'Springfield'),
    ('NY', 'Fairview'),
    ('NY', 'Georgetown'),
    ('NY', 'Madison'),
    ('NY', 'Riverside'),
    ('NY', 'Springfield'),
    ('NY', 'Buffalo'),
    ('NY', 'Syracuse'),
    ('NY', 'Rochester'),
    ('NY', 'New York City'),
    ('NY', 'Albany'),
    ('NC', 'Fairview'),
    ('NC', 'Georgetown'),
    ('NC', 'Madison'),
    ('NC', 'Riverside'),
    ('NC', 'Springfield'),
    ('ND', 'Fairview'),
    ('ND', 'Georgetown'),
    ('ND', 'Madison'),
    ('ND', 'Riverside'),
    ('ND', 'Springfield'),
    ('OH', 'Fairview'),
    ('OH', 'Georgetown'),
    ('OH', 'Madison'),
    ('OH', 'Riverside'),
    ('OH', 'Springfield'),
    ('OK', 'Fairview'),
    ('OK', 'Georgetown'),
    ('OK', 'Madison'),
    ('OK', 'Riverside'),
    ('OK', 'Springfield'),
    ('OR', 'Fairview'),
    ('OR', 'Georgetown'),
    ('OR', 'Madison'),
    ('OR', 'Riverside'),
    ('OR', 'Springfield'),
    ('PA', 'Fairview'),
    ('PA', 'Georgetown'),
    ('PA', 'Madison'),
    ('PA', 'Riverside'),
    ('PA', 'Springfield'),
    ('RI', 'Fairview'),
    ('RI', 'Georgetown'),
    ('RI', 'Madison'),
    ('RI', 'Riverside'),
    ('RI', 'Springfield'),
    ('SC', 'Fairview'),
    ('SC', 'Georgetown'),
    ('SC', 'Madison'),
    ('SC', 'Riverside'),
    ('SC', 'Springfield'),
    ('SD', 'Fairview'),
    ('SD', 'Georgetown'),
    ('SD', 'Madison'),
    ('SD', 'Riverside'),
    ('SD', 'Springfield'),
    ('TN', 'Fairview'),
    ('TN', 'Georgetown'),
    ('TN', 'Madison'),
    ('TN', 'Riverside'),
    ('TN', 'Springfield'),
    ('TX', 'Fairview'),
    ('TX', 'Georgetown'),
    ('TX', 'Madison'),
    ('TX', 'Riverside'),
    ('TX', 'Springfield'),
    ('TX', 'Austin'),
    ('TX', 'San Antonio'),
    ('TX', 'Dallas'),
    ('TX', 'Fort Worth'),
    ('TX', 'Houston'),
    ('UT', 'Fairview'),
    ('UT', 'Georgetown'),
    ('UT', 'Madison'),
    ('UT', 'Riverside'),
    ('UT', 'Springfield'),
    ('VT', 'Fairview'),
    ('VT', 'Georgetown'),
    ('VT', 'Madison'),
    ('VT', 'Riverside'),
    ('VT', 'Springfield'),
    ('VA', 'Fairview'),
    ('VA', 'Georgetown'),
    ('VA', 'Madison'),
    ('VA', 'Riverside'),
    ('VA', 'Springfield'),
    ('WA', 'Fairview'),
    ('WA', 'Georgetown'),
    ('WA', 'Madison'),
    ('WA', 'Riverside'),
    ('WA', 'Springfield'),
    ('WV', 'Fairview'),
    ('WV', 'Georgetown'),
    ('WV', 'Madison'),
    ('WV', 'Riverside'),
    ('WV', 'Springfield'),
    ('WI', 'Fairview'),
    ('WI', 'Georgetown'),
    ('WI', 'Madison'),
    ('WI', 'Riverside'),
    ('WI', 'Springfield'),
    ('WY', 'Fairview'),
    ('WY', 'Georgetown'),
    ('WY', 'Madison'),
    ('WY', 'Riverside'),
    ('WY', 'Springfield'),
    ('DC', 'Fairview'),
    ('DC', 'Georgetown'),
    ('DC', 'Madison'),
    ('DC', 'Riverside'),
    ('DC', 'Springfield'),
    ('PR', 'Fairview'),
    ('PR', 'Georgetown'),
    ('PR', 'Madison'),
    ('PR', 'Riverside'),
    ('PR', 'Springfield'),
    ('VI', 'Fairview'),
    ('VI', 'Georgetown'),
    ('VI', 'Madison'),
    ('VI', 'Riverside'),
    ('VI', 'Springfield'),
    ('GU', 'Fairview'),
    ('GU', 'Georgetown'),
    ('GU', 'Madison'),
    ('GU', 'Riverside'),
    ('GU', 'Springfield'),
    ('AS', 'Fairview'),
    ('AS', 'Georgetown'),
    ('AS', 'Madison'),
    ('AS', 'Riverside'),
    ('AS', 'Springfield'),
    ('MP', 'Fairview'),
    ('MP', 'Georgetown'),
    ('MP', 'Madison'),
    ('MP', 'Riverside'),
    ('MP', 'Springfield')
) AS c(state_code, name)
JOIN app.states st ON st.code = c.state_code
ON CONFLICT (state_id, name) DO NOTHING;

-- Códigos postales (ZIPs primarios de las ciudades reales).
INSERT INTO app.postal_codes (id, city_id, zip_code)
SELECT gen_random_uuid(), ci.id, z.zip_code
FROM (VALUES
    ('CA', 'Los Angeles', '90001'),
    ('CA', 'San Francisco', '94101'),
    ('CA', 'Sacramento', '95814'),
    ('CA', 'Fresno', '93721'),
    ('CA', 'San Diego', '92101'),
    ('TX', 'Austin', '73301'),
    ('TX', 'San Antonio', '78205'),
    ('TX', 'Dallas', '75201'),
    ('TX', 'Fort Worth', '76102'),
    ('TX', 'Houston', '77002'),
    ('FL', 'Fort Lauderdale', '33301'),
    ('FL', 'Tampa', '33602'),
    ('FL', 'Miami', '33101'),
    ('FL', 'Orlando', '32801'),
    ('FL', 'Jacksonville', '32202'),
    ('NY', 'Buffalo', '14202'),
    ('NY', 'Syracuse', '13202'),
    ('NY', 'Rochester', '14614'),
    ('NY', 'New York City', '10001'),
    ('NY', 'Albany', '12207'),
    ('IL', 'Chicago', '60601'),
    ('IL', 'Joliet', '60432'),
    ('IL', 'Rockford', '61101'),
    ('IL', 'Aurora', '60506'),
    ('IL', 'Naperville', '60540')
) AS z(state_code, city, zip_code)
JOIN app.states st ON st.code = z.state_code
JOIN app.cities ci ON ci.state_id = st.id AND ci.name = z.city
ON CONFLICT (city_id, zip_code) DO NOTHING;

-- Backfill: etnia legacy (string) -> FK al catálogo.
UPDATE app.patient_profiles p
SET ethnicity_id = e.id
FROM app.ethnicities e
WHERE p.ethnicity IS NOT NULL
  AND e.code = CASE p.ethnicity
    WHEN 'White/Caucasian' THEN 'WHITE'
    WHEN 'Hispanic/Latino' THEN 'HISPANIC_OR_LATINO'
    WHEN 'Black/African American' THEN 'BLACK_OR_AFRICAN_AMERICAN'
    WHEN 'Asian' THEN 'ASIAN'
    WHEN 'Native American' THEN 'AMERICAN_INDIAN_OR_ALASKA_NATIVE'
    WHEN 'Pacific Islander' THEN 'NATIVE_HAWAIIAN_OR_PACIFIC_ISLANDER'
    WHEN 'Two or more races' THEN 'MULTIRACIAL'
    WHEN 'Other' THEN 'OTHER' ELSE NULL
  END;

-- Backfill: grupo sanguíneo (el código legacy coincide 1:1 con el catálogo).
UPDATE app.patient_profiles p
SET blood_type_id = b.id
FROM app.blood_types b
WHERE p.blood_type IS NOT NULL AND p.blood_type = b.code;

-- Backfill: país/estado/ciudad (estados legacy en código ISO-2; las 5
-- ciudades genéricas existen en todos los estados, las reales solo en el suyo).
UPDATE app.patient_profiles p
SET country_id = c.id, state_id = s.id, city_id = ci.id
FROM app.countries c
JOIN app.states s ON s.country_id = c.id
JOIN app.cities ci ON ci.state_id = s.id
WHERE c.code = 'US'
  AND s.code = p.state
  AND ci.name = p.city
  AND p.city IS NOT NULL
  AND p.state IS NOT NULL;

-- Normalización de vocabularios legacy de estilo de vida.
UPDATE app.patient_profiles SET exercise_level = 'Light' WHERE exercise_level = 'Light (1-2x/wk)';
UPDATE app.patient_profiles SET exercise_level = 'Moderate' WHERE exercise_level = 'Moderate (3-4x/wk)';
UPDATE app.patient_profiles SET exercise_level = 'Active' WHERE exercise_level = 'Active (5+/wk)';
UPDATE app.patient_profiles SET hospitalization_history = 'None' WHERE hospitalization_history = 'No';
UPDATE app.patient_profiles SET hospitalization_history = 'Once' WHERE hospitalization_history = 'Yes - Once';
UPDATE app.patient_profiles SET hospitalization_history = 'Multiple' WHERE hospitalization_history = 'Yes - Multiple';
