-- Seed de catálogos profesionales del ERP (schema erp).
-- Idempotente: todos los INSERT usan ON CONFLICT DO NOTHING.
-- Generado por scripts/generate_professional_catalogs_seed.py; no editar a mano.

-- Profesiones (professional_types).
INSERT INTO erp.professional_types (code, name, description, sort_order) VALUES
    ('PHYSICIAN', 'Physician (MD/DO)', 'Médico/a con licencia estatal (Doctor of Medicine o Doctor of Osteopathic Medicine).', 1),
    ('NURSE_PRACTITIONER', 'Nurse Practitioner (NP)', 'Enfermero/a de práctica avanzada con prescripción.', 2),
    ('PHYSICIAN_ASSISTANT', 'Physician Assistant (PA)', 'Asistente médico con licencia bajo supervisión de un médico.', 3),
    ('REGISTERED_NURSE', 'Registered Nurse (RN)', 'Enfermero/a registrado/a.', 4),
    ('LICENSED_PRACTICAL_NURSE', 'Licensed Practical Nurse (LPN)', 'Enfermero/a práctico/a licenciado/a.', 5),
    ('CLINICAL_PSYCHOLOGIST', 'Clinical Psychologist (PhD/PsyD)', 'Psicólogo/a clínico/a con doctorado.', 6),
    ('PSYCHIATRIST', 'Psychiatrist (MD/DO)', 'Médico/a especialista en psiquiatría.', 7),
    ('CLINICAL_SOCIAL_WORKER', 'Licensed Clinical Social Worker (LCSW)', 'Trabajador/a social clínico/a licenciado/a.', 8),
    ('PROFESSIONAL_COUNSELOR', 'Licensed Professional Counselor (LPC)', 'Consejero/a profesional licenciado/a.', 9),
    ('REGISTERED_DIETITIAN', 'Registered Dietitian (RD/RDN)', 'Dietista registrado/a (Academy of Nutrition and Dietetics).', 10),
    ('PHYSICAL_THERAPIST', 'Physical Therapist (DPT)', 'Fisioterapeuta con doctorado profesional.', 11),
    ('EXERCISE_PHYSIOLOGIST', 'Exercise Physiologist', 'Fisiólogo/a del ejercicio.', 12),
    ('HEALTH_COACH', 'Certified Health Coach (NBC-HWC)', 'Coach de salud certificado/a (National Board).', 13),
    ('PHARMACIST', 'Pharmacist (PharmD)', 'Farmacéutico/a.', 14),
    ('CARE_COORDINATOR', 'Care Coordinator', 'Coordinador/a de atención al paciente.', 15),
    ('COMMUNITY_HEALTH_WORKER', 'Community Health Worker', 'Trabajador/a de salud comunitaria.', 16),
    ('MEDICAL_ASSISTANT', 'Medical Assistant', 'Asistente médico/a de consulta.', 17)
ON CONFLICT (code) DO NOTHING;

-- Especialidades (specialties).
INSERT INTO erp.specialties (code, name, category, description, sort_order) VALUES
    ('OBESITY_MEDICINE', 'Obesity Medicine', 'Medicina', 'Tratamiento integral de la obesidad (certificación ABOM).', 1),
    ('BARIATRIC_SURGERY', 'Bariatric Surgery', 'Medicina', 'Cirugía bariátrica y metabólica.', 2),
    ('ENDOCRINOLOGY', 'Endocrinology & Diabetes', 'Medicina', 'Endocrinología y metabolismo (diabetes, tiroides).', 3),
    ('FAMILY_MEDICINE', 'Family Medicine', 'Medicina', 'Medicina familiar y atención primaria.', 4),
    ('INTERNAL_MEDICINE', 'Internal Medicine', 'Medicina', 'Medicina interna del adulto.', 5),
    ('PEDIATRICS', 'Pediatrics', 'Medicina', 'Pediatría general.', 6),
    ('ADOLESCENT_MEDICINE', 'Adolescent Medicine', 'Medicina', 'Medicina del adolescente.', 7),
    ('PREVENTIVE_MEDICINE', 'Preventive Medicine', 'Medicina', 'Medicina preventiva y salud pública.', 8),
    ('LIFESTYLE_MEDICINE', 'Lifestyle Medicine', 'Medicina', 'Medicina del estilo de vida (certificación ABLM).', 9),
    ('SPORTS_MEDICINE', 'Sports Medicine', 'Medicina', 'Medicina deportiva.', 10),
    ('PHYSICAL_MEDICINE_REHAB', 'Physical Medicine & Rehabilitation', 'Medicina', 'Medicina física y rehabilitación.', 11),
    ('CARDIOLOGY', 'Cardiology', 'Medicina', 'Cardiología clínica y preventiva.', 12),
    ('GASTROENTEROLOGY', 'Gastroenterology', 'Medicina', 'Gastroenterología y hepatología.', 13),
    ('SLEEP_MEDICINE', 'Sleep Medicine', 'Medicina', 'Medicina del sueño (apnea obstructiva).', 14),
    ('CLINICAL_NUTRITION', 'Clinical Nutrition', 'Nutrición', 'Nutrición clínica y dietoterapia.', 15),
    ('PEDIATRIC_NUTRITION', 'Pediatric Nutrition', 'Nutrición', 'Nutrición pediátrica.', 16),
    ('SPORTS_NUTRITION', 'Sports Nutrition', 'Nutrición', 'Nutrición deportiva.', 17),
    ('BEHAVIORAL_HEALTH', 'Behavioral Health', 'Salud mental', 'Salud conductual y manejo de hábitos.', 18),
    ('PSYCHIATRY', 'Psychiatry', 'Salud mental', 'Psiquiatría general.', 19),
    ('CLINICAL_PSYCHOLOGY', 'Clinical Psychology', 'Salud mental', 'Psicología clínica.', 20),
    ('BARIATRIC_PSYCHOLOGY', 'Bariatric Psychology', 'Salud mental', 'Psicología pre/post cirugía bariátrica.', 21),
    ('MEDSURG_NURSING', 'Medical-Surgical Nursing', 'Enfermería', 'Enfermería médico-quirúrgica.', 22),
    ('COMMUNITY_HEALTH_NURSING', 'Community Health Nursing', 'Enfermería', 'Enfermería de salud comunitaria.', 23),
    ('PHYSICAL_THERAPY', 'Physical Therapy', 'Terapia', 'Fisioterapia y rehabilitación funcional.', 24),
    ('OCCUPATIONAL_THERAPY', 'Occupational Therapy', 'Terapia', 'Terapia ocupacional.', 25),
    ('CARE_COORDINATION', 'Care Coordination', 'Coordinación', 'Coordinación de cuidados y navegación del paciente.', 26),
    ('HEALTH_EDUCATION', 'Health Education', 'Coordinación', 'Educación para la salud y promoción.', 27),
    ('EXERCISE_PHYSIOLOGY', 'Exercise Physiology', 'Fitness', 'Fisiología del ejercicio y prescripción de actividad física.', 28),
    ('WELLNESS_COACHING', 'Wellness Coaching', 'Fitness', 'Coaching de bienestar y hábitos saludables.', 29)
ON CONFLICT (code) DO NOTHING;

-- Mapeo profesión → especialidades válidas (professional_type_specialties).
INSERT INTO erp.professional_type_specialties (professional_type_id, specialty_id)
SELECT pt.id, s.id
FROM (VALUES
    ('PHYSICIAN', 'OBESITY_MEDICINE'),
    ('PHYSICIAN', 'BARIATRIC_SURGERY'),
    ('PHYSICIAN', 'ENDOCRINOLOGY'),
    ('PHYSICIAN', 'FAMILY_MEDICINE'),
    ('PHYSICIAN', 'INTERNAL_MEDICINE'),
    ('PHYSICIAN', 'PEDIATRICS'),
    ('PHYSICIAN', 'ADOLESCENT_MEDICINE'),
    ('PHYSICIAN', 'PREVENTIVE_MEDICINE'),
    ('PHYSICIAN', 'LIFESTYLE_MEDICINE'),
    ('PHYSICIAN', 'SPORTS_MEDICINE'),
    ('PHYSICIAN', 'PHYSICAL_MEDICINE_REHAB'),
    ('PHYSICIAN', 'CARDIOLOGY'),
    ('PHYSICIAN', 'GASTROENTEROLOGY'),
    ('PHYSICIAN', 'SLEEP_MEDICINE'),
    ('PHYSICIAN', 'CLINICAL_NUTRITION'),
    ('PHYSICIAN', 'BEHAVIORAL_HEALTH'),
    ('NURSE_PRACTITIONER', 'FAMILY_MEDICINE'),
    ('NURSE_PRACTITIONER', 'INTERNAL_MEDICINE'),
    ('NURSE_PRACTITIONER', 'PEDIATRICS'),
    ('NURSE_PRACTITIONER', 'ADOLESCENT_MEDICINE'),
    ('NURSE_PRACTITIONER', 'PREVENTIVE_MEDICINE'),
    ('NURSE_PRACTITIONER', 'LIFESTYLE_MEDICINE'),
    ('NURSE_PRACTITIONER', 'OBESITY_MEDICINE'),
    ('NURSE_PRACTITIONER', 'ENDOCRINOLOGY'),
    ('NURSE_PRACTITIONER', 'BEHAVIORAL_HEALTH'),
    ('NURSE_PRACTITIONER', 'COMMUNITY_HEALTH_NURSING'),
    ('PHYSICIAN_ASSISTANT', 'FAMILY_MEDICINE'),
    ('PHYSICIAN_ASSISTANT', 'INTERNAL_MEDICINE'),
    ('PHYSICIAN_ASSISTANT', 'PEDIATRICS'),
    ('PHYSICIAN_ASSISTANT', 'OBESITY_MEDICINE'),
    ('PHYSICIAN_ASSISTANT', 'ENDOCRINOLOGY'),
    ('PHYSICIAN_ASSISTANT', 'SPORTS_MEDICINE'),
    ('PHYSICIAN_ASSISTANT', 'PREVENTIVE_MEDICINE'),
    ('REGISTERED_NURSE', 'MEDSURG_NURSING'),
    ('REGISTERED_NURSE', 'COMMUNITY_HEALTH_NURSING'),
    ('REGISTERED_NURSE', 'CARE_COORDINATION'),
    ('REGISTERED_NURSE', 'HEALTH_EDUCATION'),
    ('REGISTERED_NURSE', 'OBESITY_MEDICINE'),
    ('REGISTERED_NURSE', 'ENDOCRINOLOGY'),
    ('LICENSED_PRACTICAL_NURSE', 'MEDSURG_NURSING'),
    ('LICENSED_PRACTICAL_NURSE', 'COMMUNITY_HEALTH_NURSING'),
    ('LICENSED_PRACTICAL_NURSE', 'CARE_COORDINATION'),
    ('CLINICAL_PSYCHOLOGIST', 'CLINICAL_PSYCHOLOGY'),
    ('CLINICAL_PSYCHOLOGIST', 'BEHAVIORAL_HEALTH'),
    ('CLINICAL_PSYCHOLOGIST', 'BARIATRIC_PSYCHOLOGY'),
    ('PSYCHIATRIST', 'PSYCHIATRY'),
    ('PSYCHIATRIST', 'BEHAVIORAL_HEALTH'),
    ('CLINICAL_SOCIAL_WORKER', 'BEHAVIORAL_HEALTH'),
    ('CLINICAL_SOCIAL_WORKER', 'CARE_COORDINATION'),
    ('CLINICAL_SOCIAL_WORKER', 'HEALTH_EDUCATION'),
    ('PROFESSIONAL_COUNSELOR', 'BEHAVIORAL_HEALTH'),
    ('PROFESSIONAL_COUNSELOR', 'HEALTH_EDUCATION'),
    ('REGISTERED_DIETITIAN', 'CLINICAL_NUTRITION'),
    ('REGISTERED_DIETITIAN', 'PEDIATRIC_NUTRITION'),
    ('REGISTERED_DIETITIAN', 'SPORTS_NUTRITION'),
    ('REGISTERED_DIETITIAN', 'HEALTH_EDUCATION'),
    ('REGISTERED_DIETITIAN', 'OBESITY_MEDICINE'),
    ('PHYSICAL_THERAPIST', 'PHYSICAL_THERAPY'),
    ('EXERCISE_PHYSIOLOGIST', 'EXERCISE_PHYSIOLOGY'),
    ('EXERCISE_PHYSIOLOGIST', 'WELLNESS_COACHING'),
    ('HEALTH_COACH', 'WELLNESS_COACHING'),
    ('HEALTH_COACH', 'HEALTH_EDUCATION'),
    ('HEALTH_COACH', 'BEHAVIORAL_HEALTH'),
    ('CARE_COORDINATOR', 'CARE_COORDINATION'),
    ('CARE_COORDINATOR', 'HEALTH_EDUCATION'),
    ('COMMUNITY_HEALTH_WORKER', 'HEALTH_EDUCATION'),
    ('COMMUNITY_HEALTH_WORKER', 'COMMUNITY_HEALTH_NURSING'),
    ('COMMUNITY_HEALTH_WORKER', 'CARE_COORDINATION'),
    ('MEDICAL_ASSISTANT', 'CARE_COORDINATION'),
    ('MEDICAL_ASSISTANT', 'HEALTH_EDUCATION')
) AS m(pt_code, s_code)
JOIN erp.professional_types pt ON pt.code = m.pt_code
JOIN erp.specialties s ON s.code = m.s_code
ON CONFLICT (professional_type_id, specialty_id) DO NOTHING;
