// <auto-generated />
using System;
using CoppAddresd.Telemedicine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoppAddresd.Telemedicine.Infrastructure.Migrations
{
    [DbContext(typeof(TelemedicineDbContext))]
    [Migration("20260820204816_AddWebhookEventsTable")]
    partial class AddWebhookEventsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tele")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.AppointmentCancellation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cancelled_by");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_appointment_cancellations");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_appointment_cancellations_appointment_id");

                    b.ToTable("appointment_cancellations", "tele");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.AppointmentReschedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset>("FromStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("from_start");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("requested_by");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_user_id");

                    b.Property<DateTimeOffset>("RescheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rescheduled_at");

                    b.Property<DateTimeOffset>("ToStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("to_start");

                    b.HasKey("Id")
                        .HasName("pk_appointment_reschedules");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_appointment_reschedules_appointment_id");

                    b.ToTable("appointment_reschedules", "tele");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.ClinicalEncounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<string>("ClinicalData")
                        .HasColumnType("jsonb")
                        .HasColumnName("clinical_data");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("EncounterDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encounter_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_clinical_encounters");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_clinical_encounters_appointment_id");

                    b.HasIndex("EncounterDate")
                        .HasDatabaseName("ix_clinical_encounters_encounter_date");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_clinical_encounters_patient_id");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_clinical_encounters_professional_id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_clinical_encounters_session_id");

                    b.ToTable("clinical_encounters", "tele");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("RecipientScopeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_scope_id");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recipient_type");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<Guid?>("RelatedAppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_appointment_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_telemedicine_alerts");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_telemedicine_alerts_created_at");

                    b.HasIndex("RelatedAppointmentId")
                        .HasDatabaseName("ix_telemedicine_alerts_related_appointment_id");

                    b.HasIndex("RecipientType", "RecipientScopeId")
                        .HasDatabaseName("ix_telemedicine_alerts_recipient_type_recipient_scope_id");

                    b.HasIndex("RecipientUserId", "ReadAt")
                        .HasDatabaseName("ix_telemedicine_alerts_recipient_user_id_read_at");

                    b.ToTable("telemedicine_alerts", "tele");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineAppointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cancelled_by");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("NoShowReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("no_show_reason");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<int>("RescheduleCount")
                        .HasColumnType("integer")
                        .HasColumnName("reschedule_count");

                    b.Property<DateTimeOffset>("ScheduledEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end");

                    b.Property<DateTimeOffset>("ScheduledStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialty_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_telemedicine_appointments");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_telemedicine_appointments_patient_id");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_telemedicine_appointments_professional_id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_telemedicine_appointments_request_id");

                    b.HasIndex("ScheduledStart")
                        .HasDatabaseName("ix_telemedicine_appointments_scheduled_start");

                    b.HasIndex("SpecialtyId")
                        .HasDatabaseName("ix_telemedicine_appointments_specialty_id");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_telemedicine_appointments_organization_id_status");

                    b.HasIndex("ProfessionalId", "ScheduledStart")
                        .IsUnique()
                        .HasDatabaseName("ix_appointments_professional_start_active")
                        .HasFilter("telemedicine_appointments.status IN ('Requested','Confirmed','InProgress')");

                    b.ToTable("telemedicine_appointments", "tele");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset?>("PreferredStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preferred_start");

                    b.Property<Guid?>("ProfessionalId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uuid")
                        .HasColumnName("specialty_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_telemedicine_requests");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_telemedicine_requests_patient_id");

                    b.HasIndex("ProfessionalId")
                        .HasDatabaseName("ix_telemedicine_requests_professional_id");

                    b.HasIndex("SpecialtyId")
                        .HasDatabaseName("ix_telemedicine_requests_specialty_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_telemedicine_requests_status");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_telemedicine_requests_organization_id_status");

                    b.ToTable("telemedicine_requests", "tele");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<long?>("DurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("EndReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid?>("EndedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("ended_by");

                    b.Property<DateTimeOffset?>("LastProviderEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_provider_event_at");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_telemedicine_sessions");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_telemedicine_sessions_appointment_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_telemedicine_sessions_room_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_telemedicine_sessions_status");

                    b.ToTable("telemedicine_sessions", "tele");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessTokenTtlSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("access_token_ttl_seconds");

                    b.Property<Guid?>("ClinicId")
                        .HasColumnType("uuid")
                        .HasColumnName("clinic_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultAppointmentDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("default_appointment_duration_minutes");

                    b.Property<int>("MaxAdvanceBookingDays")
                        .HasColumnType("integer")
                        .HasColumnName("max_advance_booking_days");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<int>("MaxReschedules")
                        .HasColumnType("integer")
                        .HasColumnName("max_reschedules");

                    b.Property<int>("MinAdvanceBookingHours")
                        .HasColumnType("integer")
                        .HasColumnName("min_advance_booking_hours");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("RoomCloseAfterMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("room_close_after_minutes");

                    b.Property<int>("RoomOpenBeforeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("room_open_before_minutes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_telemedicine_settings");

                    b.HasIndex("OrganizationId", "ClinicId")
                        .IsUnique()
                        .HasDatabaseName("ix_telemedicine_settings_organization_id_clinic_id");

                    b.ToTable("telemedicine_settings", "tele");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("ParticipantSid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("participant_sid");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RoomSid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("room_sid");

                    b.HasKey("Id")
                        .HasName("pk_telemedicine_webhook_events");

                    b.HasIndex("EventType", "RoomSid", "ParticipantSid")
                        .IsUnique()
                        .HasDatabaseName("ix_telemedicine_webhook_events_event_type_room_sid_participant");

                    b.ToTable("telemedicine_webhook_events", "tele");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.VirtualRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderRoomName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_room_name");

                    b.Property<string>("ProviderRoomSid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_room_sid");

                    b.Property<DateTimeOffset>("ScheduledCloseAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_close_at");

                    b.Property<DateTimeOffset>("ScheduledOpenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_open_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_virtual_rooms");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_virtual_rooms_appointment_id");

                    b.HasIndex("ProviderRoomSid")
                        .HasDatabaseName("ix_virtual_rooms_provider_room_sid");

                    b.HasIndex("Provider", "ProviderRoomName")
                        .IsUnique()
                        .HasDatabaseName("ix_virtual_rooms_provider_provider_room_name");

                    b.ToTable("virtual_rooms", "tele");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.AppointmentCancellation", b =>
                {
                    b.HasOne("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineAppointment", "Appointment")
                        .WithMany("Cancellations")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_cancellations_telemedicine_appointments_appoint");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.AppointmentReschedule", b =>
                {
                    b.HasOne("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineAppointment", "Appointment")
                        .WithMany("Reschedules")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_reschedules_telemedicine_appointments_appointme");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.ClinicalEncounter", b =>
                {
                    b.HasOne("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineAppointment", "Appointment")
                        .WithOne("Encounter")
                        .HasForeignKey("CoppAddresd.Telemedicine.Domain.Entities.ClinicalEncounter", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_encounters_telemedicine_appointments_appointment_id");

                    b.HasOne("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineSession", "Session")
                        .WithOne("Encounter")
                        .HasForeignKey("CoppAddresd.Telemedicine.Domain.Entities.ClinicalEncounter", "SessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_clinical_encounters_sessions_session_id");

                    b.Navigation("Appointment");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineAppointment", b =>
                {
                    b.HasOne("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineRequest", "Request")
                        .WithMany("Appointments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_telemedicine_appointments_requests_request_id");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineSession", b =>
                {
                    b.HasOne("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineAppointment", "Appointment")
                        .WithMany("Sessions")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telemedicine_sessions_telemedicine_appointments_appointment");

                    b.HasOne("CoppAddresd.Telemedicine.Domain.Entities.VirtualRoom", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telemedicine_sessions_virtual_rooms_room_id");

                    b.Navigation("Appointment");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.VirtualRoom", b =>
                {
                    b.HasOne("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineAppointment", "Appointment")
                        .WithOne("Room")
                        .HasForeignKey("CoppAddresd.Telemedicine.Domain.Entities.VirtualRoom", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_virtual_rooms_telemedicine_appointments_appointment_id");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineAppointment", b =>
                {
                    b.Navigation("Cancellations");

                    b.Navigation("Encounter");

                    b.Navigation("Reschedules");

                    b.Navigation("Room");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineRequest", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.TelemedicineSession", b =>
                {
                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("CoppAddresd.Telemedicine.Domain.Entities.VirtualRoom", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
