// <auto-generated />
using System;
using CoppAddresd.Community.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoppAddresd.Community.Migrations
{
    [DbContext(typeof(CommunityDbContext))]
    [Migration("20260827171604_AddRecognitionsAndNetworks")]
    partial class AddRecognitionsAndNetworks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoppAddresd.Community.Entities.ChatGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_profile_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByProfileId");

                    b.ToTable("chat_groups", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.ChatGroupMember", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GroupId", "ProfileId");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_chat_group_members_profile_id");

                    b.ToTable("chat_group_members", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_comments_parent_comment_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_comments_post_id");

                    b.HasIndex("ProfileId");

                    b.ToTable("comments", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.FeedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_feed_events_created_at");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_feed_events_profile_id");

                    b.ToTable("feed_events", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Follow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FollowerProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_profile_id");

                    b.Property<Guid>("FollowingProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("following_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("FollowingProfileId")
                        .HasDatabaseName("ix_follows_following");

                    b.HasIndex("FollowerProfileId", "FollowingProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_follows_follower_following");

                    b.ToTable("follows", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.HasKey("Id");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_likes_comment_id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_likes_post_id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("CommentId", "ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_likes_comment_profile");

                    b.HasIndex("PostId", "ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_likes_post_profile");

                    b.ToTable("likes", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("RecipientProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_profile_id");

                    b.Property<Guid>("SenderProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_profile_id");

                    b.Property<Guid?>("TriggeredByProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("RecipientProfileId");

                    b.HasIndex("TriggeredByProfileId");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_messages_conversation_created");

                    b.HasIndex("SenderProfileId", "RecipientProfileId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_messages_sender_recipient_created");

                    b.ToTable("messages", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.NetworkChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<int>("Followers")
                        .HasColumnType("integer")
                        .HasColumnName("followers");

                    b.Property<string>("Handle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("handle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_network_channels_sort_order");

                    b.ToTable("network_channels", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.NetworkGrowthPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("month");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "Month")
                        .IsUnique()
                        .HasDatabaseName("ix_network_growth_points_channel_month");

                    b.ToTable("network_growth_points", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Destination")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("destination");

                    b.Property<bool>("Pinned")
                        .HasColumnType("boolean")
                        .HasColumnName("pinned");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_posts_created_at");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_posts_profile_id");

                    b.ToTable("posts", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_key");

                    b.Property<string>("BanReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ban_reason");

                    b.Property<DateTime?>("BannedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("banned_at");

                    b.Property<Guid?>("BannedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("banned_by");

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("best_streak");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer")
                        .HasColumnName("current_streak");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("diagnosis");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<DateTimeOffset?>("LastActiveAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_active_at");

                    b.Property<DateTimeOffset?>("LastPostAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_post_at");

                    b.Property<string>("Region")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("region");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("Week")
                        .HasColumnType("integer")
                        .HasColumnName("week");

                    b.Property<int>("XpTotal")
                        .HasColumnType("integer")
                        .HasColumnName("xp_total");

                    b.HasKey("Id");

                    b.HasIndex("Region")
                        .HasDatabaseName("ix_profiles_region");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_profiles_status");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_user_id");

                    b.ToTable("profiles", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Recognition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Sent")
                        .HasColumnName("status");

                    b.Property<Guid?>("TriggeredByProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by_profile_id");

                    b.Property<string>("TypeLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("type_label");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_recognitions_created_at");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_recognitions_profile_id");

                    b.HasIndex("TriggeredByProfileId");

                    b.ToTable("recognitions", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.XpEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_xp_entries_created_at");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_xp_entries_profile_id");

                    b.ToTable("xp_entries", "community");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.ChatGroup", b =>
                {
                    b.HasOne("CoppAddresd.Community.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("CreatedByProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.ChatGroupMember", b =>
                {
                    b.HasOne("CoppAddresd.Community.Entities.ChatGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoppAddresd.Community.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Comment", b =>
                {
                    b.HasOne("CoppAddresd.Community.Entities.Comment", null)
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CoppAddresd.Community.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoppAddresd.Community.Entities.Profile", "Profile")
                        .WithMany("Comments")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.FeedEvent", b =>
                {
                    b.HasOne("CoppAddresd.Community.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Follow", b =>
                {
                    b.HasOne("CoppAddresd.Community.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("FollowerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoppAddresd.Community.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("FollowingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Like", b =>
                {
                    b.HasOne("CoppAddresd.Community.Entities.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoppAddresd.Community.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoppAddresd.Community.Entities.Profile", "Profile")
                        .WithMany("Likes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Message", b =>
                {
                    b.HasOne("CoppAddresd.Community.Entities.ChatGroup", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoppAddresd.Community.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("RecipientProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoppAddresd.Community.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("SenderProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoppAddresd.Community.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("TriggeredByProfileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.NetworkGrowthPoint", b =>
                {
                    b.HasOne("CoppAddresd.Community.Entities.NetworkChannel", "Channel")
                        .WithMany("GrowthPoints")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Post", b =>
                {
                    b.HasOne("CoppAddresd.Community.Entities.Profile", "Profile")
                        .WithMany("Posts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Recognition", b =>
                {
                    b.HasOne("CoppAddresd.Community.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoppAddresd.Community.Entities.Profile", null)
                        .WithMany()
                        .HasForeignKey("TriggeredByProfileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.XpEntry", b =>
                {
                    b.HasOne("CoppAddresd.Community.Entities.Profile", "Profile")
                        .WithMany("XpEntries")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.ChatGroup", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Comment", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.NetworkChannel", b =>
                {
                    b.Navigation("GrowthPoints");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("CoppAddresd.Community.Entities.Profile", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Posts");

                    b.Navigation("XpEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
